# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Documented_Nerd
# Description of the Site
description: Passionate DevOps Engineer With Imagination
# URL of Image of the Site
site-image: /assets/images/logo.jpg
# Keywords of the Site
site-keywords: suraj, surajkumar, imsurajkr, documented_nerd, Documented_Nerd
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage:  /assets/images/background.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: surajkumar.devp@gmail.com
facebook_username: imsurajkr
twitter_username: imsurajkr
instagram_username: documented_nerd
linkedin_username: suraj-kumar-a02877135
github_username:  imsurajkr
youtube_channel_id: 
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: documented_nerd

# Name of the Author
author-name: Documented_Nerd
# URL for the Image of the Author
author-image: /assets/images/author.jpg
# 60 Words About the Author
author-about: A DevOps Engineer by profession. Working in Fiftyfive Technologies. My hobby is singing, designing vector.Currently learning Kubernetes and bash scripting. 
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/imsurajkr

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
