# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: secforge
# Description of the Site
description: Think of SecForge as your one-stop shop for everything security-related in the devsecops realm. It's an immersive platform teeming with interactive challenges, hands-on labs, and real-world scenarios that equip you with the practical skills and knowledge to defend against evolving threats.
# URL of Image of the Site
site-image: /assets/images/logo.jpg
# Keywords of the Site
site-keywords: secforge, imsurajkr, secforge.io, security, devsecops, opsdev, devsec 
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage:  https://images.unsplash.com/photo-1531297484001-80022131f5a1?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: surajkumar.devp@gmail.com
facebook_username: imsurajkr
twitter_username: imsurajkr
instagram_username: documented_nerd
linkedin_username: suraj-kumar-a02877135
github_username:  imsurajkr
youtube_channel_id: 
# reddit_username: /
# behance_username: /
# dribbble_username: /
# spotify_username: /

# Google Analytics
google-analytics: UA-178929388-1

# Disqus
disqus-shortname: imsurajkr-github-io

# Name of the Author
author-name: Suraj Kumar
# URL for the Image of the Author
author-image: /assets/images/author.jpg
# 60 Words About the Author
author-about: Passionate and experienced DevSecOps Engineer , proficient in securing cloud environments across AWS, Azure, and GCP. Proven ability to implement security best practices, build CI/CD pipelines, and leverage Kubernetes for containerized deployments.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/imsurajkr

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
